ARG FROM

#### PRODUCTION Stage

FROM ${FROM} AS production

ARG REPOS_LIST
ARG PACKAGES_LIST

# Copy ROS Packages
COPY /raya_tasks_examples /robot/src/raya_tasks_examples

# Labels
LABEL REPO_NAME=${REPO_NAME}
LABEL COMPONENT_NAME=${COMPONENT_NAME}
LABEL REPO_METADATA=${REPO_METADATA}
LABEL COMPONENT_METADATA=${COMPONENT_METADATA}
